[pytest]


markers=
        smoke:mark test as a smoke test cases
        regression: mark test as a regression test cases


addopts = -s -v
;        --html=reports/report.html --self-contained-html --capture=tee-sys
;         --alluredir=reports/allure-results
         --headed

